/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DnnuvUservoice {
    }
}
declare global {
    interface HTMLDnnuvUservoiceElement extends Components.DnnuvUservoice, HTMLStencilElement {
    }
    var HTMLDnnuvUservoiceElement: {
        prototype: HTMLDnnuvUservoiceElement;
        new (): HTMLDnnuvUservoiceElement;
    };
    interface HTMLElementTagNameMap {
        "dnnuv-uservoice": HTMLDnnuvUservoiceElement;
    }
}
declare namespace LocalJSX {
    interface DnnuvUservoice {
    }
    interface IntrinsicElements {
        "dnnuv-uservoice": DnnuvUservoice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "dnnuv-uservoice": LocalJSX.DnnuvUservoice & JSXBase.HTMLAttributes<HTMLDnnuvUservoiceElement>;
        }
    }
}
