<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateMSBuildEditorConfigFile>false</GenerateMSBuildEditorConfigFile>
    <LangVersion>latest</LangVersion>
    <OutputType>Library</OutputType>
    <RuntimeIdentifier>win</RuntimeIdentifier>
    <RootNamespace>DNN.Modules.UserVoice</RootNamespace>
    <AssemblyName>DNN.Modules.UserVoice</AssemblyName>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\DNN.Modules.UserVoice.xml</DocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\DNN.Modules.UserVoice.xml</DocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup>
    <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="artifacts\**" />
    <Compile Remove="Combined\**" />
    <Compile Remove="docs\**" />
    <Compile Remove="IntegrationTests\**" />
    <Compile Remove="module.web\**" />
    <Compile Remove="TestResults\**" />
    <Compile Remove="UnitTests\**" />
    <Compile Remove="_build\**" />
    <EmbeddedResource Remove="artifacts\**" />
    <EmbeddedResource Remove="Combined\**" />
    <EmbeddedResource Remove="docs\**" />
    <EmbeddedResource Remove="IntegrationTests\**" />
    <EmbeddedResource Remove="module.web\**" />
    <EmbeddedResource Remove="TestResults\**" />
    <EmbeddedResource Remove="UnitTests\**" />
    <EmbeddedResource Remove="_build\**" />
    <None Remove="artifacts\**" />
    <None Remove="Combined\**" />
    <None Remove="docs\**" />
    <None Remove="IntegrationTests\**" />
    <None Remove="module.web\**" />
    <None Remove="TestResults\**" />
    <None Remove="UnitTests\**" />
    <None Remove="_build\**" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include=".gitignore" />
    <Resource Include="resources\views\view.html" />
    <Resource Include="LICENSE" />
    <Resource Include="manifest.dnn" />
    <Resource Include="ReleaseNotes.html" />
    <Resource Include="build.cmd" />
    <Resource Include="global.json" />
  </ItemGroup>
  <ItemGroup>
    <Content Include=".editorconfig" />
    <AdditionalFiles Include="stylecop.json" />
    <Content Include="README.md" />
    <Content Include="resources\images\module-icon.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="DotNetNuke.Abstractions">
      <Version>10.2.2</Version>
    </PackageReference>
    <PackageReference Include="DotNetNuke.Core">
      <Version>10.2.2</Version>
    </PackageReference>
    <PackageReference Include="DotNetNuke.Instrumentation">
      <Version>10.2.2</Version>
    </PackageReference>
    <PackageReference Include="DotNetNuke.Web">
      <Version>10.2.2</Version>
    </PackageReference>
    <PackageReference Include="DotNetNuke.WebApi">
      <Version>10.2.2</Version>
    </PackageReference>
    <PackageReference Include="EntityFramework">
      <Version>6.5.1</Version>
    </PackageReference>
    <PackageReference Include="FluentValidation">
      <Version>11.12.0</Version>
    </PackageReference>
    <PackageReference Include="Humanizer" Version="3.0.1" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core">
      <Version>5.3.0</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers">
      <Version>10.0.102</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.3</Version>
    </PackageReference>
    <PackageReference Include="NSwag.Annotations">
      <Version>14.6.3</Version>
    </PackageReference>
    <PackageReference Include="OneOf">
      <Version>3.0.271</Version>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers">
      <Version>1.1.118</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>