//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.

//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNN.Modules.UserVoice.Services.Localization
{
    using DotNetNuke.Common.Utilities;
    using DotNetNuke.Services.Localization;
    using System.Diagnostics.CodeAnalysis;
    using System.Web.Hosting;
    using System.Threading;
    using static DNN.Modules.UserVoice.Services.Localization.LocalizationViewModel;

    /// <summary>
    /// Provides strongly typed localization services for this module.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class LocalizationService : ILocalizationService
    {
        private readonly ILocalizationProvider localizationProvider;
        private readonly LocalizationViewModel viewModel;
        private readonly string cacheKey;
        private string resourceFileRoot;

        private string ResourceFileRoot
        {
            get
            {
                if (string.IsNullOrWhiteSpace(this.resourceFileRoot))
                {
                    this.resourceFileRoot = "~/DesktopModules/DNN.UserVoice/resources/App_LocalResources/";
                }

                return this.resourceFileRoot;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizationService"/> class.
        /// </summary>
        public LocalizationService()
        {
            this.localizationProvider = new LocalizationProvider();
            this.cacheKey = "DNN.Modules.UserVoice" + "_Localization_" + Thread.CurrentThread.CurrentCulture;
            this.viewModel = new LocalizationViewModel();
            var viewModel = DataCache.GetCache<LocalizationViewModel>(this.cacheKey);
            if (viewModel is null)
            {
                viewModel = this.HydrateViewModel();
                DataCache.SetCache(this.cacheKey, viewModel);
            }
            this.viewModel = viewModel;
        }

        /// <summary>
        /// A viewmodel that strongly types all resource keys.
        /// </summary>
        public LocalizationViewModel ViewModel
        {
            get
            {
                return this.viewModel;
            }
        }

        private string GetString(string key, string file)
        {
            return this.localizationProvider.GetString(key, this.ResourceFileRoot + file);
        }

        private LocalizationViewModel HydrateViewModel()
        {
            var modelvalidation = new ModelValidationInfo
            {
                AllVotesUsed = this.GetString("AllVotesUsed", "ModelValidation.resx"),
                CannotEditIdeaNotYours = this.GetString("CannotEditIdeaNotYours", "ModelValidation.resx"),
                DescriptionRequired = this.GetString("DescriptionRequired", "ModelValidation.resx"),
                DescriptionTooLong = this.GetString("DescriptionTooLong", "ModelValidation.resx"),
                IdeaNotFound = this.GetString("IdeaNotFound", "ModelValidation.resx"),
                IdGreaterThanZero = this.GetString("IdGreaterThanZero", "ModelValidation.resx"),
                ModuleRequired = this.GetString("ModuleRequired", "ModelValidation.resx"),
                TitleRequired = this.GetString("TitleRequired", "ModelValidation.resx"),
                TitleTooLong = this.GetString("TitleTooLong", "ModelValidation.resx"),
                TitleUnique = this.GetString("TitleUnique", "ModelValidation.resx"),
                UserRequired = this.GetString("UserRequired", "ModelValidation.resx"),
                ValidationErrorTitle = this.GetString("ValidationErrorTitle", "ModelValidation.resx"),
                VotesExhausted = this.GetString("VotesExhausted", "ModelValidation.resx"),

            };
            viewModel.ModelValidation = modelvalidation;
            var ui = new UIInfo
            {
                BackToIdeas = this.GetString("BackToIdeas", "UI.resx"),
                Cancel = this.GetString("Cancel", "UI.resx"),
                Create = this.GetString("Create", "UI.resx"),
                CreatedBy = this.GetString("CreatedBy", "UI.resx"),
                Delete = this.GetString("Delete", "UI.resx"),
                Description = this.GetString("Description", "UI.resx"),
                LoginToPost = this.GetString("LoginToPost", "UI.resx"),
                No = this.GetString("No", "UI.resx"),
                PostIdea = this.GetString("PostIdea", "UI.resx"),
                Save = this.GetString("Save", "UI.resx"),
                SearchIdeasPlaceholder = this.GetString("SearchIdeasPlaceholder", "UI.resx"),
                Submit = this.GetString("Submit", "UI.resx"),
                Title = this.GetString("Title", "UI.resx"),
                Vote = this.GetString("Vote", "UI.resx"),
                Votes = this.GetString("Votes", "UI.resx"),
                Withdraw = this.GetString("Withdraw", "UI.resx"),
                Yes = this.GetString("Yes", "UI.resx"),

            };
            viewModel.UI = ui;
            return viewModel;

        }
    }
}

