//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.

//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNN.Modules.UserVoice.Services.Localization
{
    using System.Diagnostics.CodeAnalysis;

    /// <summary>
    /// A viewmodel that exposes all resource keys in strong types.
    /// </summary>
    [ExcludeFromCodeCoverage]
    public class LocalizationViewModel
    {
        /// <summary>
        /// Localized strings present in the ModelValidation resources.
        /// </summary>
        public ModelValidationInfo ModelValidation { get; set; } = new ModelValidationInfo();

        /// <summary>
        /// Localized strings present in the UI resources.
        /// </summary>
        public UIInfo UI { get; set; } = new UIInfo();
        /// <summary>
        /// Localized strings for the ModelValidation resources.
        /// </summary>
        public class ModelValidationInfo
        {
            /// <summary>Gets or sets the AllVotesUsed localized text.</summary>
            /// <example>You have already used all of your votes, withdraw votes if you want to vote on other ideas.</example>
            public string AllVotesUsed { get; set; } = "You have already used all of your votes, withdraw votes if you want to vote on other ideas.";

            /// <summary>Gets or sets the CannotEditIdeaNotYours localized text.</summary>
            /// <example>You cannot edit this idea because it was not created by you</example>
            public string CannotEditIdeaNotYours { get; set; } = "You cannot edit this idea because it was not created by you";

            /// <summary>Gets or sets the DescriptionRequired localized text.</summary>
            /// <example>A description is required</example>
            public string DescriptionRequired { get; set; } = "A description is required";

            /// <summary>Gets or sets the DescriptionTooLong localized text.</summary>
            /// <example>The description is limited to {0} characters</example>
            public string DescriptionTooLong { get; set; } = "The description is limited to {0} characters";

            /// <summary>Gets or sets the IdeaNotFound localized text.</summary>
            /// <example>The Idea specified was not found</example>
            public string IdeaNotFound { get; set; } = "The Idea specified was not found";

            /// <summary>Gets or sets the IdGreaterThanZero localized text.</summary>
            /// <example>The Id must be an integer bigger than 0</example>
            public string IdGreaterThanZero { get; set; } = "The Id must be an integer bigger than 0";

            /// <summary>Gets or sets the ModuleRequired localized text.</summary>
            /// <example>A ModuleID is required</example>
            public string ModuleRequired { get; set; } = "A ModuleID is required";

            /// <summary>Gets or sets the TitleRequired localized text.</summary>
            /// <example>The title is required</example>
            public string TitleRequired { get; set; } = "The title is required";

            /// <summary>Gets or sets the TitleTooLong localized text.</summary>
            /// <example>The title is limited to {0} characters</example>
            public string TitleTooLong { get; set; } = "The title is limited to {0} characters";

            /// <summary>Gets or sets the TitleUnique localized text.</summary>
            /// <example>Titles must be unique and another item already exists with this title</example>
            public string TitleUnique { get; set; } = "Titles must be unique and another item already exists with this title";

            /// <summary>Gets or sets the UserRequired localized text.</summary>
            /// <example>The user is required</example>
            public string UserRequired { get; set; } = "The user is required";

            /// <summary>Gets or sets the ValidationErrorTitle localized text.</summary>
            /// <example>Validation Error</example>
            public string ValidationErrorTitle { get; set; } = "Validation Error";

            /// <summary>Gets or sets the VotesExhausted localized text.</summary>
            /// <example>You have used all your available votes. You can withdraw some votes if you want to vote on other ideas.</example>
            public string VotesExhausted { get; set; } = "You have used all your available votes. You can withdraw some votes if you want to vote on other ideas.";


        }

        /// <summary>
        /// Localized strings for the UI resources.
        /// </summary>
        public class UIInfo
        {
            /// <summary>Gets or sets the BackToIdeas localized text.</summary>
            /// <example>Back To Ideas</example>
            public string BackToIdeas { get; set; } = "Back To Ideas";

            /// <summary>Gets or sets the Cancel localized text.</summary>
            /// <example>Cancel</example>
            public string Cancel { get; set; } = "Cancel";

            /// <summary>Gets or sets the Create localized text.</summary>
            /// <example>Create</example>
            public string Create { get; set; } = "Create";

            /// <summary>Gets or sets the CreatedBy localized text.</summary>
            /// <example>Created by</example>
            public string CreatedBy { get; set; } = "Created by";

            /// <summary>Gets or sets the Delete localized text.</summary>
            /// <example>Delete</example>
            public string Delete { get; set; } = "Delete";

            /// <summary>Gets or sets the Description localized text.</summary>
            /// <example>Description</example>
            public string Description { get; set; } = "Description";

            /// <summary>Gets or sets the LoginToPost localized text.</summary>
            /// <example>Please login to submit a new idea.</example>
            public string LoginToPost { get; set; } = "Please login to submit a new idea.";

            /// <summary>Gets or sets the No localized text.</summary>
            /// <example>No</example>
            public string No { get; set; } = "No";

            /// <summary>Gets or sets the PostIdea localized text.</summary>
            /// <example>Post New Idea</example>
            public string PostIdea { get; set; } = "Post New Idea";

            /// <summary>Gets or sets the Save localized text.</summary>
            /// <example>Save</example>
            public string Save { get; set; } = "Save";

            /// <summary>Gets or sets the SearchIdeasPlaceholder localized text.</summary>
            /// <example>Describe your idea...</example>
            public string SearchIdeasPlaceholder { get; set; } = "Describe your idea...";

            /// <summary>Gets or sets the Submit localized text.</summary>
            /// <example>Submit</example>
            public string Submit { get; set; } = "Submit";

            /// <summary>Gets or sets the Title localized text.</summary>
            /// <example>Title</example>
            public string Title { get; set; } = "Title";

            /// <summary>Gets or sets the Vote localized text.</summary>
            /// <example>Vote</example>
            public string Vote { get; set; } = "Vote";

            /// <summary>Gets or sets the Votes localized text.</summary>
            /// <example>Votes</example>
            public string Votes { get; set; } = "Votes";

            /// <summary>Gets or sets the Withdraw localized text.</summary>
            /// <example>Withdraw</example>
            public string Withdraw { get; set; } = "Withdraw";

            /// <summary>Gets or sets the Yes localized text.</summary>
            /// <example>Yes</example>
            public string Yes { get; set; } = "Yes";


        }


    }
}
