//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { DnnServicesFramework } from '@dnncommunity/dnn-elements';
export class ClientBase {

  private sf: DnnServicesFramework;
  private moduleId: number;

  constructor(configuration: ConfigureRequest) {
    this.moduleId = configuration.moduleId;
    this.sf = new DnnServicesFramework(this.moduleId);
  }

  protected getBaseUrl(_defaultUrl: string, baseUrl?: string): string {
    baseUrl = this.sf.getServiceRoot("DNNCommunity_UserVoice");

    // Strips the last / if present for future concatenations
    baseUrl = baseUrl.replace(/\/$/, "");

    return baseUrl || "";
  }

  protected transformOptions(options: RequestInit): Promise<RequestInit> {
    const dnnHeaders = this.sf.getModuleHeaders();

    let headers: Headers;
    if (!options.headers) {
      headers = new Headers();
    } else if (options.headers instanceof Headers) {
      headers = options.headers;
    } else if (Array.isArray(options.headers)) {
      headers = new Headers(options.headers);
    } else {
      headers = new Headers(Object.entries(options.headers));
    }

    dnnHeaders.forEach((value, key) => {
      headers.append(key, value);
    });

    options.headers = headers;

    return Promise.resolve(options);
  }
}

export class IdeaClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(configuration: ConfigureRequest, baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super(configuration);
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * Saves (creates or updates) an idea.
     * @param dto (optional) The information to save.
     * @return The idea was saved successfully.
     */
    saveIdea(dto: SaveIdeaDto | null | undefined, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/Idea/SaveIdea";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processSaveIdea(_response);
        });
    }

    protected processSaveIdea(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = resultData400 ? ProblemDetails.fromJS(resultData400) : null as any;
            return throwException("An error has occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Searches for ideas that match the specified criteria and returns a paged list of results.
     * @param dto (optional) An object containing the search criteria to filter ideas. Cannot be null.
     * @return The ideas were retrieved successfully.
     */
    searchIdeas(dto: SearchIdeasDto | null | undefined, signal?: AbortSignal): Promise<PagedListOfIdeaViewModel | null> {
        let url_ = this.baseUrl + "/Idea/SearchIdeas";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processSearchIdeas(_response);
        });
    }

    protected processSearchIdeas(response: Response): Promise<PagedListOfIdeaViewModel | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? PagedListOfIdeaViewModel.fromJS(resultData200) : null as any;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<PagedListOfIdeaViewModel | null>(null as any);
    }

    /**
     * Submits a request to delete an idea based on the provided deletion details.
     * @param dto (optional) An object containing the details required to request deletion of an idea. Cannot be null.
     * @return The idea deletion request was submitted successfully.
     */
    requestIdeaDeletion(dto: RequestIdeaDeletionDto | null | undefined, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/Idea/RequestIdeaDeletion";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processRequestIdeaDeletion(_response);
        });
    }

    protected processRequestIdeaDeletion(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = resultData400 ? ProblemDetails.fromJS(resultData400) : null as any;
            return throwException("An error has occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Retrieves the details of a specific idea by its unique identifier.
     * @param id The unique identifier of the idea to retrieve. Must be a valid idea ID.
     * @return The idea details were retrieved successfully.
     */
    getIdeaDetails(id: number, signal?: AbortSignal): Promise<IdeaDetailsViewModel | null> {
        let url_ = this.baseUrl + "/Idea/GetIdeaDetails?";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined and cannot be null.");
        else
            url_ += "id=" + encodeURIComponent("" + id) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGetIdeaDetails(_response);
        });
    }

    protected processGetIdeaDetails(response: Response): Promise<IdeaDetailsViewModel | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? IdeaDetailsViewModel.fromJS(resultData200) : null as any;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<IdeaDetailsViewModel | null>(null as any);
    }
}

export class LocalizationClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(configuration: ConfigureRequest, baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super(configuration);
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * Gets localization keys and values.
     * @return OK
     */
    getLocalization(signal?: AbortSignal): Promise<LocalizationViewModel | null> {
        let url_ = this.baseUrl + "/Localization/GetLocalization";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGetLocalization(_response);
        });
    }

    protected processGetLocalization(response: Response): Promise<LocalizationViewModel | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? LocalizationViewModel.fromJS(resultData200) : null as any;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LocalizationViewModel | null>(null as any);
    }
}

export class SettingsClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(configuration: ConfigureRequest, baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super(configuration);
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * Retrieves the current configuration settings for the UserVoice module.
     * @return The settings of the UserVoice module.
     */
    getSettings(signal?: AbortSignal): Promise<UserVoiceSettings | null> {
        let url_ = this.baseUrl + "/Settings/GetSettings";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGetSettings(_response);
        });
    }

    protected processGetSettings(response: Response): Promise<UserVoiceSettings | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? UserVoiceSettings.fromJS(resultData200) : null as any;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<UserVoiceSettings | null>(null as any);
    }

    /**
     * Updates the module settings with the specified values.
     * @param settings (optional) The settings to apply to the UserVoice module. Cannot be null.
     * @return An HTTP response indicating the result of the update operation.
     */
    updateSettings(settings: UserVoiceSettings | null | undefined, signal?: AbortSignal): Promise<FileResponse> {
        let url_ = this.baseUrl + "/Settings/UpdateSettings";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(settings);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processUpdateSettings(_response);
        });
    }

    protected processUpdateSettings(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }
}

export class VotingClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(configuration: ConfigureRequest, baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super(configuration);
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * Retrieves aggregated voting statistics for the current user.
     * @return The voting statistics were retrieved successfully.
     */
    getVotingStats(signal?: AbortSignal): Promise<VoteStatsViewModel | null> {
        let url_ = this.baseUrl + "/Voting/GetVotingStats";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGetVotingStats(_response);
        });
    }

    protected processGetVotingStats(response: Response): Promise<VoteStatsViewModel | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? VoteStatsViewModel.fromJS(resultData200) : null as any;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<VoteStatsViewModel | null>(null as any);
    }

    /**
     * Registers an upvote for the specified idea on behalf of the current user.
     * @param dto (optional) An object containing the details of the idea to upvote. Must not be null.
     * @return An HTTP response indicating the result of the upvote operation. Returns 200 OK if the upvote is successful;
                otherwise, returns 400 Bad Request with problem details.
     */
    upvoteIdea(dto: VoteDto | null | undefined, signal?: AbortSignal): Promise<FileResponse> {
        let url_ = this.baseUrl + "/Voting/UpvoteIdea";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processUpvoteIdea(_response);
        });
    }

    protected processUpvoteIdea(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status === 400) {
            return response.text().then((_responseText) => {
            let result400: any = null;
            let resultData400 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result400 = resultData400 ? ProblemDetails.fromJS(resultData400) : null as any;
            return throwException("A server side error occurred.", status, _responseText, _headers, result400);
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }

    /**
     * Removes a user's vote from the specified idea.
     * @param dto (optional) An object containing the details of the vote to be removed. Cannot be null.
     * @return An HTTP response indicating the result of the remove vote operation.
     */
    removeVote(dto: VoteDto | null | undefined, signal?: AbortSignal): Promise<FileResponse> {
        let url_ = this.baseUrl + "/Voting/RemoveVote";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(dto);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/octet-stream"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processRemoveVote(_response);
        });
    }

    protected processRemoveVote(response: Response): Promise<FileResponse> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200 || status === 206) {
            const contentDisposition = response.headers ? response.headers.get("content-disposition") : undefined;
            let fileNameMatch = contentDisposition ? /filename\*=(?:(\\?['"])(.*?)\1|(?:[^\s]+'.*?')?([^;\n]*))/g.exec(contentDisposition) : undefined;
            let fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[3] || fileNameMatch[2] : undefined;
            if (fileName) {
                fileName = decodeURIComponent(fileName);
            } else {
                fileNameMatch = contentDisposition ? /filename="?([^"]*?)"?(;|$)/g.exec(contentDisposition) : undefined;
                fileName = fileNameMatch && fileNameMatch.length > 1 ? fileNameMatch[1] : undefined;
            }
            return response.blob().then(blob => { return { fileName: fileName, data: blob, status: status, headers: _headers }; });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<FileResponse>(null as any);
    }
}

/** Implements RFC 7807 Problem Details for HTTP APIs. */
export class ProblemDetails implements IProblemDetails {
    /** Gets or sets a URI that describes the type of problem. */
    type?: string | undefined;
    /** Gets or sets the title of the problem. */
    title?: string | undefined;
    /** Gets or sets the status code. */
    status?: number;
    /** Gets or sets a human readable string explaining the problem in more details. */
    detail?: string | undefined;
    /** Gets or sets the url that caused the instance of this problem. */
    instance?: string | undefined;
    /** Gets or sets the collection of error messages associated with the current operation or object. */
    errors?: string[] | undefined;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["Type"];
            this.title = _data["Title"];
            this.status = _data["Status"];
            this.detail = _data["Detail"];
            this.instance = _data["Instance"];
            if (Array.isArray(_data["Errors"])) {
                this.errors = [] as any;
                for (let item of _data["Errors"])
                    this.errors!.push(item);
            }
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Type"] = this.type;
        data["Title"] = this.title;
        data["Status"] = this.status;
        data["Detail"] = this.detail;
        data["Instance"] = this.instance;
        if (Array.isArray(this.errors)) {
            data["Errors"] = [];
            for (let item of this.errors)
                data["Errors"].push(item);
        }
        return data;
    }
}

/** Implements RFC 7807 Problem Details for HTTP APIs. */
export interface IProblemDetails {
    /** Gets or sets a URI that describes the type of problem. */
    type?: string | undefined;
    /** Gets or sets the title of the problem. */
    title?: string | undefined;
    /** Gets or sets the status code. */
    status?: number;
    /** Gets or sets a human readable string explaining the problem in more details. */
    detail?: string | undefined;
    /** Gets or sets the url that caused the instance of this problem. */
    instance?: string | undefined;
    /** Gets or sets the collection of error messages associated with the current operation or object. */
    errors?: string[] | undefined;
}

/** Represents the data transfer object used to submit or update an idea for saving operations. */
export class SaveIdeaDto implements ISaveIdeaDto {
    /** Gets or sets the unique identifier of the idea (only required for updates). */
    id?: number;
    /** Gets or sets the title associated with the idea. */
    title?: string | undefined;
    /** Gets or sets the descriptive text associated with the idea. */
    description?: string | undefined;

    constructor(data?: ISaveIdeaDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.title = _data["Title"];
            this.description = _data["Description"];
        }
    }

    static fromJS(data: any): SaveIdeaDto {
        data = typeof data === 'object' ? data : {};
        let result = new SaveIdeaDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Title"] = this.title;
        data["Description"] = this.description;
        return data;
    }
}

/** Represents the data transfer object used to submit or update an idea for saving operations. */
export interface ISaveIdeaDto {
    /** Gets or sets the unique identifier of the idea (only required for updates). */
    id?: number;
    /** Gets or sets the title associated with the idea. */
    title?: string | undefined;
    /** Gets or sets the descriptive text associated with the idea. */
    description?: string | undefined;
}

/** Presents a list of entities in pages. */
export class PagedListOfIdeaViewModel implements IPagedListOfIdeaViewModel {
    /** Gets the items for this page. */
    items?: IdeaViewModel[] | undefined;
    /** Gets the page number for the current page. */
    page?: number;
    /** Gets the amount of entities per page. */
    pageSize?: number;
    /** Gets the total number of entities available in all pages. */
    resultCount?: number;
    /** Gets the total number of available pages. */
    pageCount?: number;

    constructor(data?: IPagedListOfIdeaViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["Items"])) {
                this.items = [] as any;
                for (let item of _data["Items"])
                    this.items!.push(IdeaViewModel.fromJS(item));
            }
            this.page = _data["Page"];
            this.pageSize = _data["PageSize"];
            this.resultCount = _data["ResultCount"];
            this.pageCount = _data["PageCount"];
        }
    }

    static fromJS(data: any): PagedListOfIdeaViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new PagedListOfIdeaViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.items)) {
            data["Items"] = [];
            for (let item of this.items)
                data["Items"].push(item ? item.toJSON() : undefined as any);
        }
        data["Page"] = this.page;
        data["PageSize"] = this.pageSize;
        data["ResultCount"] = this.resultCount;
        data["PageCount"] = this.pageCount;
        return data;
    }
}

/** Presents a list of entities in pages. */
export interface IPagedListOfIdeaViewModel {
    /** Gets the items for this page. */
    items?: IdeaViewModel[] | undefined;
    /** Gets the page number for the current page. */
    page?: number;
    /** Gets the amount of entities per page. */
    pageSize?: number;
    /** Gets the total number of entities available in all pages. */
    resultCount?: number;
    /** Gets the total number of available pages. */
    pageCount?: number;
}

/** Basic information about an idea. */
export class IdeaViewModel implements IIdeaViewModel {
    /** Gets or sets the unique identifier for the idea. */
    id?: number;
    /** Gets or sets the title associated with the idea. */
    title?: string | undefined;
    /** Gets or sets the description associated with the object. */
    description?: string | undefined;
    /** Gets or sets the number of votes associated with the idea. */
    votes?: number;
    /** Gets or sets a value indicating whether the current user has voted for this item. */
    isVotedByUser?: boolean;

    constructor(data?: IIdeaViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.title = _data["Title"];
            this.description = _data["Description"];
            this.votes = _data["Votes"];
            this.isVotedByUser = _data["IsVotedByUser"];
        }
    }

    static fromJS(data: any): IdeaViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new IdeaViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Title"] = this.title;
        data["Description"] = this.description;
        data["Votes"] = this.votes;
        data["IsVotedByUser"] = this.isVotedByUser;
        return data;
    }
}

/** Basic information about an idea. */
export interface IIdeaViewModel {
    /** Gets or sets the unique identifier for the idea. */
    id?: number;
    /** Gets or sets the title associated with the idea. */
    title?: string | undefined;
    /** Gets or sets the description associated with the object. */
    description?: string | undefined;
    /** Gets or sets the number of votes associated with the idea. */
    votes?: number;
    /** Gets or sets a value indicating whether the current user has voted for this item. */
    isVotedByUser?: boolean;
}

/** The details about ideas search to perform. */
export class SearchIdeasDto implements ISearchIdeasDto {
    /** Gets or sets the current page number for paginated results. */
    page?: number;
    /** Gets or sets the number of items to include on each page of results. */
    pageSize?: number;
    /** Gets or sets the string to search for. */
    query?: string | undefined;
    /** Gets or sets a value indicating whether only ideas created by the current user are included. */
    onlyMyIdeas?: boolean;

    constructor(data?: ISearchIdeasDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.page = _data["Page"];
            this.pageSize = _data["PageSize"];
            this.query = _data["Query"];
            this.onlyMyIdeas = _data["OnlyMyIdeas"];
        }
    }

    static fromJS(data: any): SearchIdeasDto {
        data = typeof data === 'object' ? data : {};
        let result = new SearchIdeasDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Page"] = this.page;
        data["PageSize"] = this.pageSize;
        data["Query"] = this.query;
        data["OnlyMyIdeas"] = this.onlyMyIdeas;
        return data;
    }
}

/** The details about ideas search to perform. */
export interface ISearchIdeasDto {
    /** Gets or sets the current page number for paginated results. */
    page?: number;
    /** Gets or sets the number of items to include on each page of results. */
    pageSize?: number;
    /** Gets or sets the string to search for. */
    query?: string | undefined;
    /** Gets or sets a value indicating whether only ideas created by the current user are included. */
    onlyMyIdeas?: boolean;
}

/** Information required to soft-delete an idea. */
export class RequestIdeaDeletionDto implements IRequestIdeaDeletionDto {
    /** Gets or sets the ID of the idea to be deleted. */
    id?: number;

    constructor(data?: IRequestIdeaDeletionDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
        }
    }

    static fromJS(data: any): RequestIdeaDeletionDto {
        data = typeof data === 'object' ? data : {};
        let result = new RequestIdeaDeletionDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        return data;
    }
}

/** Information required to soft-delete an idea. */
export interface IRequestIdeaDeletionDto {
    /** Gets or sets the ID of the idea to be deleted. */
    id?: number;
}

/** Represents the view model for displaying details related to an idea. */
export class IdeaDetailsViewModel implements IIdeaDetailsViewModel {
    /** Gets or sets the unique identifier for the entity. */
    id?: number;
    /** Gets or sets the title associated with the idea. */
    title?: string | undefined;
    /** Gets or sets the descriptive text associated with the idea. */
    description?: string | undefined;
    /** Gets or sets a value indicating whether the current user has permission to edit the idea. */
    canEdit?: boolean;
    /** Gets or sets the display name of the user who created the entity. */
    createdByUserDisplayName?: string | undefined;
    /** Gets or sets the date and time when the idea was created. */
    createdAt?: Date;
    /** Gets or sets a value indicating how long ago the idea was created, in a human-readable format (e.g., "2 hours ago"). */
    createdSince?: string | undefined;
    /** Gets or sets the number of votes associated with the idea. */
    votes?: number;

    constructor(data?: IIdeaDetailsViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["Id"];
            this.title = _data["Title"];
            this.description = _data["Description"];
            this.canEdit = _data["CanEdit"];
            this.createdByUserDisplayName = _data["CreatedByUserDisplayName"];
            this.createdAt = _data["CreatedAt"] ? new Date(_data["CreatedAt"].toString()) : undefined as any;
            this.createdSince = _data["CreatedSince"];
            this.votes = _data["Votes"];
        }
    }

    static fromJS(data: any): IdeaDetailsViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new IdeaDetailsViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Id"] = this.id;
        data["Title"] = this.title;
        data["Description"] = this.description;
        data["CanEdit"] = this.canEdit;
        data["CreatedByUserDisplayName"] = this.createdByUserDisplayName;
        data["CreatedAt"] = this.createdAt ? this.createdAt.toISOString() : undefined as any;
        data["CreatedSince"] = this.createdSince;
        data["Votes"] = this.votes;
        return data;
    }
}

/** Represents the view model for displaying details related to an idea. */
export interface IIdeaDetailsViewModel {
    /** Gets or sets the unique identifier for the entity. */
    id?: number;
    /** Gets or sets the title associated with the idea. */
    title?: string | undefined;
    /** Gets or sets the descriptive text associated with the idea. */
    description?: string | undefined;
    /** Gets or sets a value indicating whether the current user has permission to edit the idea. */
    canEdit?: boolean;
    /** Gets or sets the display name of the user who created the entity. */
    createdByUserDisplayName?: string | undefined;
    /** Gets or sets the date and time when the idea was created. */
    createdAt?: Date;
    /** Gets or sets a value indicating how long ago the idea was created, in a human-readable format (e.g., "2 hours ago"). */
    createdSince?: string | undefined;
    /** Gets or sets the number of votes associated with the idea. */
    votes?: number;
}

/** A viewmodel that exposes all resource keys in strong types. */
export class LocalizationViewModel implements ILocalizationViewModel {
    /** Localized strings present in the ModelValidation resources. */
    modelValidation?: ModelValidationInfo | undefined;
    /** Localized strings present in the UI resources. */
    uI?: UIInfo | undefined;

    constructor(data?: ILocalizationViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.modelValidation = _data["ModelValidation"] ? ModelValidationInfo.fromJS(_data["ModelValidation"]) : undefined as any;
            this.uI = _data["UI"] ? UIInfo.fromJS(_data["UI"]) : undefined as any;
        }
    }

    static fromJS(data: any): LocalizationViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new LocalizationViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ModelValidation"] = this.modelValidation ? this.modelValidation.toJSON() : undefined as any;
        data["UI"] = this.uI ? this.uI.toJSON() : undefined as any;
        return data;
    }
}

/** A viewmodel that exposes all resource keys in strong types. */
export interface ILocalizationViewModel {
    /** Localized strings present in the ModelValidation resources. */
    modelValidation?: ModelValidationInfo | undefined;
    /** Localized strings present in the UI resources. */
    uI?: UIInfo | undefined;
}

/** Localized strings for the ModelValidation resources. */
export class ModelValidationInfo implements IModelValidationInfo {
    /** Gets or sets the CannotEditIdeaNotYours localized text. */
    cannotEditIdeaNotYours?: string | undefined;
    /** Gets or sets the DescriptionRequired localized text. */
    descriptionRequired?: string | undefined;
    /** Gets or sets the DescriptionTooLong localized text. */
    descriptionTooLong?: string | undefined;
    /** Gets or sets the IdeaNotFound localized text. */
    ideaNotFound?: string | undefined;
    /** Gets or sets the IdGreaterThanZero localized text. */
    idGreaterThanZero?: string | undefined;
    /** Gets or sets the ModuleRequired localized text. */
    moduleRequired?: string | undefined;
    /** Gets or sets the TitleRequired localized text. */
    titleRequired?: string | undefined;
    /** Gets or sets the TitleTooLong localized text. */
    titleTooLong?: string | undefined;
    /** Gets or sets the TitleUnique localized text. */
    titleUnique?: string | undefined;
    /** Gets or sets the UserRequired localized text. */
    userRequired?: string | undefined;
    /** Gets or sets the ValidationErrorTitle localized text. */
    validationErrorTitle?: string | undefined;
    /** Gets or sets the VotesExhausted localized text. */
    votesExhausted?: string | undefined;

    constructor(data?: IModelValidationInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.cannotEditIdeaNotYours = _data["CannotEditIdeaNotYours"];
            this.descriptionRequired = _data["DescriptionRequired"];
            this.descriptionTooLong = _data["DescriptionTooLong"];
            this.ideaNotFound = _data["IdeaNotFound"];
            this.idGreaterThanZero = _data["IdGreaterThanZero"];
            this.moduleRequired = _data["ModuleRequired"];
            this.titleRequired = _data["TitleRequired"];
            this.titleTooLong = _data["TitleTooLong"];
            this.titleUnique = _data["TitleUnique"];
            this.userRequired = _data["UserRequired"];
            this.validationErrorTitle = _data["ValidationErrorTitle"];
            this.votesExhausted = _data["VotesExhausted"];
        }
    }

    static fromJS(data: any): ModelValidationInfo {
        data = typeof data === 'object' ? data : {};
        let result = new ModelValidationInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["CannotEditIdeaNotYours"] = this.cannotEditIdeaNotYours;
        data["DescriptionRequired"] = this.descriptionRequired;
        data["DescriptionTooLong"] = this.descriptionTooLong;
        data["IdeaNotFound"] = this.ideaNotFound;
        data["IdGreaterThanZero"] = this.idGreaterThanZero;
        data["ModuleRequired"] = this.moduleRequired;
        data["TitleRequired"] = this.titleRequired;
        data["TitleTooLong"] = this.titleTooLong;
        data["TitleUnique"] = this.titleUnique;
        data["UserRequired"] = this.userRequired;
        data["ValidationErrorTitle"] = this.validationErrorTitle;
        data["VotesExhausted"] = this.votesExhausted;
        return data;
    }
}

/** Localized strings for the ModelValidation resources. */
export interface IModelValidationInfo {
    /** Gets or sets the CannotEditIdeaNotYours localized text. */
    cannotEditIdeaNotYours?: string | undefined;
    /** Gets or sets the DescriptionRequired localized text. */
    descriptionRequired?: string | undefined;
    /** Gets or sets the DescriptionTooLong localized text. */
    descriptionTooLong?: string | undefined;
    /** Gets or sets the IdeaNotFound localized text. */
    ideaNotFound?: string | undefined;
    /** Gets or sets the IdGreaterThanZero localized text. */
    idGreaterThanZero?: string | undefined;
    /** Gets or sets the ModuleRequired localized text. */
    moduleRequired?: string | undefined;
    /** Gets or sets the TitleRequired localized text. */
    titleRequired?: string | undefined;
    /** Gets or sets the TitleTooLong localized text. */
    titleTooLong?: string | undefined;
    /** Gets or sets the TitleUnique localized text. */
    titleUnique?: string | undefined;
    /** Gets or sets the UserRequired localized text. */
    userRequired?: string | undefined;
    /** Gets or sets the ValidationErrorTitle localized text. */
    validationErrorTitle?: string | undefined;
    /** Gets or sets the VotesExhausted localized text. */
    votesExhausted?: string | undefined;
}

/** Localized strings for the UI resources. */
export class UIInfo implements IUIInfo {
    /** Gets or sets the BackToIdeas localized text. */
    backToIdeas?: string | undefined;
    /** Gets or sets the Cancel localized text. */
    cancel?: string | undefined;
    /** Gets or sets the Create localized text. */
    create?: string | undefined;
    /** Gets or sets the CreatedBy localized text. */
    createdBy?: string | undefined;
    /** Gets or sets the Delete localized text. */
    delete?: string | undefined;
    /** Gets or sets the Description localized text. */
    description?: string | undefined;
    /** Gets or sets the LoginToPost localized text. */
    loginToPost?: string | undefined;
    /** Gets or sets the No localized text. */
    no?: string | undefined;
    /** Gets or sets the PostIdea localized text. */
    postIdea?: string | undefined;
    /** Gets or sets the Save localized text. */
    save?: string | undefined;
    /** Gets or sets the SearchIdeasPlaceholder localized text. */
    searchIdeasPlaceholder?: string | undefined;
    /** Gets or sets the Submit localized text. */
    submit?: string | undefined;
    /** Gets or sets the Title localized text. */
    title?: string | undefined;
    /** Gets or sets the Vote localized text. */
    vote?: string | undefined;
    /** Gets or sets the Votes localized text. */
    votes?: string | undefined;
    /** Gets or sets the VotesLeft localized text. */
    votesLeft?: string | undefined;
    /** Gets or sets the Withdraw localized text. */
    withdraw?: string | undefined;
    /** Gets or sets the Yes localized text. */
    yes?: string | undefined;

    constructor(data?: IUIInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.backToIdeas = _data["BackToIdeas"];
            this.cancel = _data["Cancel"];
            this.create = _data["Create"];
            this.createdBy = _data["CreatedBy"];
            this.delete = _data["Delete"];
            this.description = _data["Description"];
            this.loginToPost = _data["LoginToPost"];
            this.no = _data["No"];
            this.postIdea = _data["PostIdea"];
            this.save = _data["Save"];
            this.searchIdeasPlaceholder = _data["SearchIdeasPlaceholder"];
            this.submit = _data["Submit"];
            this.title = _data["Title"];
            this.vote = _data["Vote"];
            this.votes = _data["Votes"];
            this.votesLeft = _data["VotesLeft"];
            this.withdraw = _data["Withdraw"];
            this.yes = _data["Yes"];
        }
    }

    static fromJS(data: any): UIInfo {
        data = typeof data === 'object' ? data : {};
        let result = new UIInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["BackToIdeas"] = this.backToIdeas;
        data["Cancel"] = this.cancel;
        data["Create"] = this.create;
        data["CreatedBy"] = this.createdBy;
        data["Delete"] = this.delete;
        data["Description"] = this.description;
        data["LoginToPost"] = this.loginToPost;
        data["No"] = this.no;
        data["PostIdea"] = this.postIdea;
        data["Save"] = this.save;
        data["SearchIdeasPlaceholder"] = this.searchIdeasPlaceholder;
        data["Submit"] = this.submit;
        data["Title"] = this.title;
        data["Vote"] = this.vote;
        data["Votes"] = this.votes;
        data["VotesLeft"] = this.votesLeft;
        data["Withdraw"] = this.withdraw;
        data["Yes"] = this.yes;
        return data;
    }
}

/** Localized strings for the UI resources. */
export interface IUIInfo {
    /** Gets or sets the BackToIdeas localized text. */
    backToIdeas?: string | undefined;
    /** Gets or sets the Cancel localized text. */
    cancel?: string | undefined;
    /** Gets or sets the Create localized text. */
    create?: string | undefined;
    /** Gets or sets the CreatedBy localized text. */
    createdBy?: string | undefined;
    /** Gets or sets the Delete localized text. */
    delete?: string | undefined;
    /** Gets or sets the Description localized text. */
    description?: string | undefined;
    /** Gets or sets the LoginToPost localized text. */
    loginToPost?: string | undefined;
    /** Gets or sets the No localized text. */
    no?: string | undefined;
    /** Gets or sets the PostIdea localized text. */
    postIdea?: string | undefined;
    /** Gets or sets the Save localized text. */
    save?: string | undefined;
    /** Gets or sets the SearchIdeasPlaceholder localized text. */
    searchIdeasPlaceholder?: string | undefined;
    /** Gets or sets the Submit localized text. */
    submit?: string | undefined;
    /** Gets or sets the Title localized text. */
    title?: string | undefined;
    /** Gets or sets the Vote localized text. */
    vote?: string | undefined;
    /** Gets or sets the Votes localized text. */
    votes?: string | undefined;
    /** Gets or sets the VotesLeft localized text. */
    votesLeft?: string | undefined;
    /** Gets or sets the Withdraw localized text. */
    withdraw?: string | undefined;
    /** Gets or sets the Yes localized text. */
    yes?: string | undefined;
}

/** Represents the UserVoice module settings. */
export class UserVoiceSettings implements IUserVoiceSettings {
    /** Gets or sets the default number of votes allocated to each user. */
    baseVotesPerUser?: number;

    constructor(data?: IUserVoiceSettings) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.baseVotesPerUser = _data["BaseVotesPerUser"];
        }
    }

    static fromJS(data: any): UserVoiceSettings {
        data = typeof data === 'object' ? data : {};
        let result = new UserVoiceSettings();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["BaseVotesPerUser"] = this.baseVotesPerUser;
        return data;
    }
}

/** Represents the UserVoice module settings. */
export interface IUserVoiceSettings {
    /** Gets or sets the default number of votes allocated to each user. */
    baseVotesPerUser?: number;
}

/** Represents voting statistics for a user. */
export class VoteStatsViewModel implements IVoteStatsViewModel {
    /** Gets or sets the total number of votes already cast by the user. */
    currentVotes?: number;
    /** Gets or sets the maximum number of votes allowed for the user. */
    maxVotes?: number;

    constructor(data?: IVoteStatsViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.currentVotes = _data["CurrentVotes"];
            this.maxVotes = _data["MaxVotes"];
        }
    }

    static fromJS(data: any): VoteStatsViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new VoteStatsViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["CurrentVotes"] = this.currentVotes;
        data["MaxVotes"] = this.maxVotes;
        return data;
    }
}

/** Represents voting statistics for a user. */
export interface IVoteStatsViewModel {
    /** Gets or sets the total number of votes already cast by the user. */
    currentVotes?: number;
    /** Gets or sets the maximum number of votes allowed for the user. */
    maxVotes?: number;
}

/** Information about the vote to cast or remove. */
export class VoteDto implements IVoteDto {
    /** Gets or sets the ID of the idea being voted on. */
    ideaId?: number;

    constructor(data?: IVoteDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.ideaId = _data["IdeaId"];
        }
    }

    static fromJS(data: any): VoteDto {
        data = typeof data === 'object' ? data : {};
        let result = new VoteDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["IdeaId"] = this.ideaId;
        return data;
    }
}

/** Information about the vote to cast or remove. */
export interface IVoteDto {
    /** Gets or sets the ID of the idea being voted on. */
    ideaId?: number;
}

export interface FileResponse {
    data: Blob;
    status: number;
    fileName?: string;
    headers?: { [name: string]: any };
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

export interface ConfigureRequest {
  moduleId: number;
}