//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import { DnnServicesFramework } from '@dnncommunity/dnn-elements';
export class ClientBase {

  private sf: DnnServicesFramework;
  private moduleId: number;

  constructor(configuration: ConfigureRequest) {
    this.moduleId = configuration.moduleId;
    this.sf = new DnnServicesFramework(this.moduleId);
  }

  protected getBaseUrl(_defaultUrl: string, baseUrl?: string): string {
    baseUrl = this.sf.getServiceRoot("DNNCommunity_UserVoice");

    // Strips the last / if present for future concatenations
    baseUrl = baseUrl.replace(/\/$/, "");

    return baseUrl || "";
  }

  protected transformOptions(options: RequestInit): Promise<RequestInit> {
    const dnnHeaders = this.sf.getModuleHeaders();

    let headers: Headers;
    if (!options.headers) {
      headers = new Headers();
    } else if (options.headers instanceof Headers) {
      headers = options.headers;
    } else if (Array.isArray(options.headers)) {
      headers = new Headers(options.headers);
    } else {
      headers = new Headers(Object.entries(options.headers));
    }

    dnnHeaders.forEach((value, key) => {
      headers.append(key, value);
    });

    options.headers = headers;

    return Promise.resolve(options);
  }
}

export class LocalizationClient extends ClientBase {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(configuration: ConfigureRequest, baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        super(configuration);
        this.http = http ? http : window as any;
        this.baseUrl = this.getBaseUrl("", baseUrl);
    }

    /**
     * Gets localization keys and values.
     * @return OK
     */
    getLocalization(signal?: AbortSignal): Promise<LocalizationViewModel | null> {
        let url_ = this.baseUrl + "/Localization/GetLocalization";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "application/json"
            }
        };

        return this.transformOptions(options_).then(transformedOptions_ => {
            return this.http.fetch(url_, transformedOptions_);
        }).then((_response: Response) => {
            return this.processGetLocalization(_response);
        });
    }

    protected processGetLocalization(response: Response): Promise<LocalizationViewModel | null> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = resultData200 ? LocalizationViewModel.fromJS(resultData200) : null as any;
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<LocalizationViewModel | null>(null as any);
    }
}

/** A viewmodel that exposes all resource keys in strong types. */
export class LocalizationViewModel implements ILocalizationViewModel {
    /** Localized strings present in the ModelValidation resources. */
    modelValidation?: ModelValidationInfo | undefined;
    /** Localized strings present in the UI resources. */
    uI?: UIInfo | undefined;

    constructor(data?: ILocalizationViewModel) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.modelValidation = _data["ModelValidation"] ? ModelValidationInfo.fromJS(_data["ModelValidation"]) : undefined as any;
            this.uI = _data["UI"] ? UIInfo.fromJS(_data["UI"]) : undefined as any;
        }
    }

    static fromJS(data: any): LocalizationViewModel {
        data = typeof data === 'object' ? data : {};
        let result = new LocalizationViewModel();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["ModelValidation"] = this.modelValidation ? this.modelValidation.toJSON() : undefined as any;
        data["UI"] = this.uI ? this.uI.toJSON() : undefined as any;
        return data;
    }
}

/** A viewmodel that exposes all resource keys in strong types. */
export interface ILocalizationViewModel {
    /** Localized strings present in the ModelValidation resources. */
    modelValidation?: ModelValidationInfo | undefined;
    /** Localized strings present in the UI resources. */
    uI?: UIInfo | undefined;
}

/** Localized strings for the ModelValidation resources. */
export class ModelValidationInfo implements IModelValidationInfo {
    /** Gets or sets the CannotEditIdeaNotYours localized text. */
    cannotEditIdeaNotYours?: string | undefined;
    /** Gets or sets the DescriptionRequired localized text. */
    descriptionRequired?: string | undefined;
    /** Gets or sets the DescriptionTooLong localized text. */
    descriptionTooLong?: string | undefined;
    /** Gets or sets the IdeaNotFound localized text. */
    ideaNotFound?: string | undefined;
    /** Gets or sets the IdGreaterThanZero localized text. */
    idGreaterThanZero?: string | undefined;
    /** Gets or sets the ModuleRequired localized text. */
    moduleRequired?: string | undefined;
    /** Gets or sets the TitleRequired localized text. */
    titleRequired?: string | undefined;
    /** Gets or sets the TitleTooLong localized text. */
    titleTooLong?: string | undefined;
    /** Gets or sets the TitleUnique localized text. */
    titleUnique?: string | undefined;
    /** Gets or sets the UserRequired localized text. */
    userRequired?: string | undefined;

    constructor(data?: IModelValidationInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.cannotEditIdeaNotYours = _data["CannotEditIdeaNotYours"];
            this.descriptionRequired = _data["DescriptionRequired"];
            this.descriptionTooLong = _data["DescriptionTooLong"];
            this.ideaNotFound = _data["IdeaNotFound"];
            this.idGreaterThanZero = _data["IdGreaterThanZero"];
            this.moduleRequired = _data["ModuleRequired"];
            this.titleRequired = _data["TitleRequired"];
            this.titleTooLong = _data["TitleTooLong"];
            this.titleUnique = _data["TitleUnique"];
            this.userRequired = _data["UserRequired"];
        }
    }

    static fromJS(data: any): ModelValidationInfo {
        data = typeof data === 'object' ? data : {};
        let result = new ModelValidationInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["CannotEditIdeaNotYours"] = this.cannotEditIdeaNotYours;
        data["DescriptionRequired"] = this.descriptionRequired;
        data["DescriptionTooLong"] = this.descriptionTooLong;
        data["IdeaNotFound"] = this.ideaNotFound;
        data["IdGreaterThanZero"] = this.idGreaterThanZero;
        data["ModuleRequired"] = this.moduleRequired;
        data["TitleRequired"] = this.titleRequired;
        data["TitleTooLong"] = this.titleTooLong;
        data["TitleUnique"] = this.titleUnique;
        data["UserRequired"] = this.userRequired;
        return data;
    }
}

/** Localized strings for the ModelValidation resources. */
export interface IModelValidationInfo {
    /** Gets or sets the CannotEditIdeaNotYours localized text. */
    cannotEditIdeaNotYours?: string | undefined;
    /** Gets or sets the DescriptionRequired localized text. */
    descriptionRequired?: string | undefined;
    /** Gets or sets the DescriptionTooLong localized text. */
    descriptionTooLong?: string | undefined;
    /** Gets or sets the IdeaNotFound localized text. */
    ideaNotFound?: string | undefined;
    /** Gets or sets the IdGreaterThanZero localized text. */
    idGreaterThanZero?: string | undefined;
    /** Gets or sets the ModuleRequired localized text. */
    moduleRequired?: string | undefined;
    /** Gets or sets the TitleRequired localized text. */
    titleRequired?: string | undefined;
    /** Gets or sets the TitleTooLong localized text. */
    titleTooLong?: string | undefined;
    /** Gets or sets the TitleUnique localized text. */
    titleUnique?: string | undefined;
    /** Gets or sets the UserRequired localized text. */
    userRequired?: string | undefined;
}

/** Localized strings for the UI resources. */
export class UIInfo implements IUIInfo {
    /** Gets or sets the Cancel localized text. */
    cancel?: string | undefined;
    /** Gets or sets the Create localized text. */
    create?: string | undefined;
    /** Gets or sets the Delete localized text. */
    delete?: string | undefined;
    /** Gets or sets the No localized text. */
    no?: string | undefined;
    /** Gets or sets the Save localized text. */
    save?: string | undefined;
    /** Gets or sets the SearchPlaceholder localized text. */
    searchPlaceholder?: string | undefined;
    /** Gets or sets the ShownItems localized text. */
    shownItems?: string | undefined;
    /** Gets or sets the Yes localized text. */
    yes?: string | undefined;

    constructor(data?: IUIInfo) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.cancel = _data["Cancel"];
            this.create = _data["Create"];
            this.delete = _data["Delete"];
            this.no = _data["No"];
            this.save = _data["Save"];
            this.searchPlaceholder = _data["SearchPlaceholder"];
            this.shownItems = _data["ShownItems"];
            this.yes = _data["Yes"];
        }
    }

    static fromJS(data: any): UIInfo {
        data = typeof data === 'object' ? data : {};
        let result = new UIInfo();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["Cancel"] = this.cancel;
        data["Create"] = this.create;
        data["Delete"] = this.delete;
        data["No"] = this.no;
        data["Save"] = this.save;
        data["SearchPlaceholder"] = this.searchPlaceholder;
        data["ShownItems"] = this.shownItems;
        data["Yes"] = this.yes;
        return data;
    }
}

/** Localized strings for the UI resources. */
export interface IUIInfo {
    /** Gets or sets the Cancel localized text. */
    cancel?: string | undefined;
    /** Gets or sets the Create localized text. */
    create?: string | undefined;
    /** Gets or sets the Delete localized text. */
    delete?: string | undefined;
    /** Gets or sets the No localized text. */
    no?: string | undefined;
    /** Gets or sets the Save localized text. */
    save?: string | undefined;
    /** Gets or sets the SearchPlaceholder localized text. */
    searchPlaceholder?: string | undefined;
    /** Gets or sets the ShownItems localized text. */
    shownItems?: string | undefined;
    /** Gets or sets the Yes localized text. */
    yes?: string | undefined;
}

export class ApiException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isApiException = true;

    static isApiException(obj: any): obj is ApiException {
        return obj.isApiException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new ApiException(message, status, response, headers, null);
}

export interface ConfigureRequest {
  moduleId: number;
}